### ISSUE TITLE
RHEL/Centos 7, Heimdal package is not found

### ISSUE THREAD

**Issue by atomicturtle** [greenbone/openvas-smb#18]
This had been an issue in 1.0.2 as well, and a patch for 1.0.2 was posted to the mailing list. Given the changes in 1.0.3 this approach is no longer compatible. 

Note that the following 7.5 heimdal packages are available from the EPEL repo:

[root@c7-64-dev-scott openvas-smb-1.0.3]# rpm -qa |grep heimdal
heimdal-devel-7.5.0-1.el7.x86_64
heimdal-libs-7.5.0-1.el7.x86_64

[root@c7-64-dev-scott openvas-smb-1.0.3]# cmake3 -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONFDIR=/etc/ -DLOCALSTATEDIR=/var
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Perl: /usr/bin/perl (found version "5.16.3") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- Install prefix: /usr
-- Checking for module 'gnutls>=3.2.15'
--   Found gnutls, version 3.3.26
-- Checking for module 'heimdal-gssapi>=1.6.0'
--   No package 'heimdal-gssapi' found
CMake Error at /usr/share/cmake3/Modules/FindPkgConfig.cmake:418 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindPkgConfig.cmake:585 (_pkg_check_modules_internal)
  CMakeLists.txt:146 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/root/src/openvas-smb-1.0.3/CMakeFiles/CMakeOutput.log".

**Comment by cfi-gb** [comment]
@atomicturtle 

In contrast to e.g. the [gnutls packages](https://centos.pkgs.org/7/centos-x86_64/gnutls-devel-3.3.26-9.el7.x86_64.rpm.html) used in the openvas-smb [CMakeLists.txt ](https://github.com/greenbone/openvas-smb/blob/v1.0.3/CMakeLists.txt#L145) the references [heimdal-devel packages](https://centos.pkgs.org/7/epel-x86_64/heimdal-devel-7.5.0-1.el7.x86_64.rpm.html) are not pkgconfig aware.

Solving this might be a matter of contact the maintainer of the heimdal-devel packages to get pkgconfig support within this packages and the build should work without any custom modifications.

**Comment by kroosec** [comment]
Not related to openvas-smb dev. Please check with the relevant heimdal-devel packagers.

**Comment by 00willo** [comment]
For the those arriving via goole, an issue has been raised in the upstream project https://github.com/heimdal/heimdal/issues/765 for this. There's also a downstream bug in RedHat's bugzilla to cover the packaging fix for this.
* https://bugzilla.redhat.com/show_bug.cgi?id=1525462 (CentOS7)
* https://bugzilla.redhat.com/show_bug.cgi?id=1931072 (CentOS8)
