### ISSUE TITLE
Kerberos authentication

### ISSUE THREAD

**Issue by nisani33** [greenbone/openvas-smb#27]
Hi everyone,
When I try to scan my network with SMB authentication the user connects to the machines via NTLM authenticated.
Is there a way to force the user to authenticate with Kerberos only?

Thanks

**Comment by cfi-gb** [comment]
@nisani33 Please note that this issue tracker isn't a support forum to ask questions like this. As the same question was already asked at the community portal here:

https://community.greenbone.net/t/windows-authenticated-smb-scan-using-kerberos/5940

i'm closing this issue as invalid.

Thanks for your understanding and for helping to keep the communication channels clean (bugreports at the github issue trackers, support questions at the community portal).
